In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(0)
anime_sales = np.random.randint(20, size=(7,4))
anime_sales

array([[12, 15,  0,  3],
       [ 3,  7,  9, 19],
       [18,  4,  6, 12],
       [ 1,  6,  7, 14],
       [17,  5, 13,  8],
       [ 9, 19, 16, 19],
       [ 5, 15, 15,  0]])

In [3]:
df=pd.DataFrame(anime_sales,index=["Mon","Tue","Wed","Thur","Fri","Sat","Sun"],
                columns=["Demon Slayer","Hunter X Hunter","Jujutsu Kaisen","Death Note"])
df

Demon Slayer  Hunter X Hunter  Jujutsu Kaisen  Death Note
Mon             12               15               0           3
Tue              3                7               9          19
Wed             18                4               6          12
Thur             1                6               7          14
Fri             17                5              13           8
Sat              9               19              16          19
Sun              5               15              15           0

In [4]:
price=np.array([10,15,8,20])
price

array([10, 15,  8, 20])

In [5]:
price_df=pd.DataFrame(price.reshape(1,4),index=["Price"],
                      columns=["Demon Slayer","Hunter X Hunter","Jujutsu Kaisen","Death Note"])
price_df

Demon Slayer  Hunter X Hunter  Jujutsu Kaisen  Death Note
Price            10               15               8          20

In [6]:
Total_sales=np.dot(anime_sales,price)
Total_sales

array([405, 587, 528, 436, 509, 883, 395])

In [7]:
df["Total ($)"]=Total_sales
df

Demon Slayer  Hunter X Hunter  Jujutsu Kaisen  Death Note  Total ($)
Mon             12               15               0           3        405
Tue              3                7               9          19        587
Wed             18                4               6          12        528
Thur             1                6               7          14        436
Fri             17                5              13           8        509
Sat              9               19              16          19        883
Sun              5               15              15           0        395