# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1=np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2=np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape,a1.dtype,type(a1), a1.size, a1.ndim

((3,), dtype('int32'), numpy.ndarray, 3, 1)

In [4]:
# Attributes of 2-dimensional array
a2.shape, a1.size, a1.ndim, a2.dtype, type(a2), 

((2, 3), 3, 1, dtype('int32'), numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
a3.shape, a1.size, a1.ndim, a3.dtype,type(a3), 

((1, 3, 3), 3, 1, dtype('int32'), numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df=pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [7]:
# Create an array of shape (10, 2) with only ones
one=np.ones((10,2))
one

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zero=np.zeros((7,2,3))
zero

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
a=np.arange(0,100,3)
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a=np.random.randint(10,size=(7,2))
a

array([[7, 3],
       [5, 4],
       [7, 8],
       [9, 7],
       [5, 9],
       [0, 2],
       [3, 7]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a=np.random.rand(3,5)
a

array([[0.0520724 , 0.55213881, 0.90394788, 0.41233982, 0.52800603],
       [0.58780656, 0.68494925, 0.84767962, 0.81823545, 0.80510387],
       [0.90951434, 0.55194492, 0.04199635, 0.53078542, 0.81942047]])

In [12]:
# Set the random seed to 42
np.random.seed(0)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(10,size=(4,6))


array([[5, 0, 3, 3, 7, 9],
       [3, 5, 2, 4, 7, 6],
       [8, 8, 1, 6, 7, 7],
       [8, 1, 5, 9, 8, 9]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
np.random.seed(0)
a=np.random.randint(1,10,size=(3,7))

# Find the unique numbers in the array you just created
b=np.unique(a)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a

array([[6, 1, 4, 4, 8, 4, 6],
       [3, 5, 8, 7, 9, 9, 2],
       [7, 8, 8, 9, 2, 6, 9]])

In [15]:
# Find the 0'th index of the latest array you created
a[0]

array([6, 1, 4, 4, 8, 4, 6])

In [16]:
# Get the first 2 rows of latest array you created
a[0:2]

array([[6, 1, 4, 4, 8, 4, 6],
       [3, 5, 8, 7, 9, 9, 2]])

In [17]:
# Get the first 2 values of the first 2 rows of the latest array
a[0:2,0:2]

array([[6, 1],
       [3, 5]])

In [18]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a=np.random.randint(10,size=(3,5))
b=np.ones((3,5))
one,a

(array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]]))

In [19]:
# Add the two arrays together
a+b

array([[10.,  5.,  4.,  1.,  4.],
       [ 6.,  1.,  3.,  4.,  9.],
       [ 2.,  4.,  4.,  4.,  8.]])

In [20]:
# Create another array of ones of shape (5, 3)
c=np.ones((5,3))

In [21]:
# Try add the array of ones and the other most recent array together
a1=a+b+c.T
a1

array([[11.,  6.,  5.,  2.,  5.],
       [ 7.,  2.,  4.,  5., 10.],
       [ 3.,  5.,  5.,  5.,  9.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [22]:
# Create another array of ones of shape (3, 5)
b=np.ones((3,5))

In [23]:
# Subtract the new array of ones from the other most recent array
a1-b

array([[10.,  5.,  4.,  1.,  4.],
       [ 6.,  1.,  3.,  4.,  9.],
       [ 2.,  4.,  4.,  4.,  8.]])

In [24]:
# Multiply the ones array with the latest array
po=b*a1
po

array([[11.,  6.,  5.,  2.,  5.],
       [ 7.,  2.,  4.,  5., 10.],
       [ 3.,  5.,  5.,  5.,  9.]])

In [25]:
# Take the latest array to the power of 2 using '**'
po**2

array([[121.,  36.,  25.,   4.,  25.],
       [ 49.,   4.,  16.,  25., 100.],
       [  9.,  25.,  25.,  25.,  81.]])

In [26]:
# Do the same thing with np.square()
np.square(po)

array([[121.,  36.,  25.,   4.,  25.],
       [ 49.,   4.,  16.,  25., 100.],
       [  9.,  25.,  25.,  25.,  81.]])

In [27]:
# Find the mean of the latest array using np.mean()
np.mean(po)

5.6

In [28]:
# Find the maximum of the latest array using np.max()
np.max(po)

11.0

In [29]:
# Find the minimum of the latest array using np.min()
np.min(po)

2.0

In [30]:
# Find the standard deviation of the latest array
np.std(po)

2.5768197453450252

In [31]:
# Find the variance of the latest array
np.var(po)

6.640000000000001

In [32]:
# Reshape the latest array to (3, 5, 1)
np.reshape(po,(3,5,1))

array([[[11.],
        [ 6.],
        [ 5.],
        [ 2.],
        [ 5.]],

       [[ 7.],
        [ 2.],
        [ 4.],
        [ 5.],
        [10.]],

       [[ 3.],
        [ 5.],
        [ 5.],
        [ 5.],
        [ 9.]]])

In [33]:
po.shape

(3, 5)

In [34]:
# Transpose the latest array
po.T

array([[11.,  7.,  3.],
       [ 6.,  2.,  5.],
       [ 5.,  4.,  5.],
       [ 2.,  5.,  5.],
       [ 5., 10.,  9.]])

What does the transpose do?

In [35]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a=np.random.randint(10,size=(3,3))
b=np.random.randint(10,size=(3,2))
a,b

(array([[0, 1, 9],
        [9, 0, 4],
        [7, 3, 2]]),
 array([[7, 2],
        [0, 0],
        [4, 5]]))

In [36]:
# Perform a dot product on the two newest arrays you created
np.dot(a,b)

array([[36, 45],
       [79, 38],
       [57, 24]])

In [37]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
c=np.random.randint(10,size=(4,3))
d=np.random.randint(10,size=(4,3))

In [38]:
# Perform a dot product on the two newest arrays you created
np.dot(c,d) 

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

=> By using Transpose

In [40]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(c,d.T)

array([[111,  47, 117,  92],
       [ 63,  30,  53,  44],
       [111,  79,  76,  74],
       [ 84,  21, 119,  86]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [41]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a=np.random.randint(10,size=(2,5))
b=np.random.randint(10,size=(2,5))
a,b

(array([[4, 4, 3, 4, 4],
        [8, 4, 3, 7, 5]]),
 array([[5, 0, 1, 5, 9],
        [3, 0, 5, 0, 1]]))

In [42]:
# Compare the two arrays with '>'
a>b

array([[False,  True,  True, False, False],
       [ True,  True, False,  True,  True]])

What happens when you compare the arrays with `>`?

In [43]:
# Compare the two arrays with '>='
a>=b

array([[False,  True,  True, False, False],
       [ True,  True, False,  True,  True]])

In [44]:
# Find which elements of the first array are greater than 7
a>7

array([[False, False, False, False, False],
       [ True, False, False, False, False]])

In [45]:
# Which parts of each array are equal? (try using '==')
a==b

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [46]:
# Sort one of the arrays you just created in ascending order
np.sort(a)

array([[3, 4, 4, 4, 4],
       [3, 4, 5, 7, 8]])

In [47]:
# Sort one of the arrays you just created in descending order
-np.sort(-a)

array([[4, 4, 4, 4, 3],
       [8, 7, 5, 4, 3]])

In [48]:
# Sort the indexes of one of the arrays you just created
np.argsort(a)

array([[2, 0, 1, 3, 4],
       [2, 1, 4, 3, 0]], dtype=int64)

In [49]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a)

5

In [50]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a)

2

In [51]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(a,axis=1)

array([0, 0], dtype=int64)

In [52]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmax(a,axis=0)

array([1, 0, 0, 1, 1], dtype=int64)

In [53]:
# Create an array of normally distributed random numbers
np.random.randn(3,5)

array([[-0.02818223,  0.42833187,  0.06651722,  0.3024719 , -0.63432209],
       [-0.36274117, -0.67246045, -0.35955316, -0.81314628, -1.7262826 ],
       [ 0.17742614, -0.40178094, -1.63019835,  0.46278226, -0.90729836]])

In [54]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.