In [1]:
import numpy as np

In [2]:
a1 = np.arange(20).reshape(10,2)
a1

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [3]:
sdr=np.random.randint(2,100,size =(3,5))
sdr

array([[73,  5,  3, 90, 42],
       [66, 63,  7, 33, 72],
       [42, 13, 36, 83, 50]])

In [4]:
a=np.ones((2,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
a=np.random.random((8,2))

In [6]:
a.size

16

In [7]:
a.shape

(8, 2)

In [8]:
a.dtype

dtype('float64')

In [9]:
a.dtype

dtype('float64')

In [10]:
np.random.seed(seed=0)
sdr=np.random.rand(1000,3)

sdr

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       ...,
       [0.47521403, 0.28729288, 0.87968154],
       [0.28492705, 0.94168707, 0.54613275],
       [0.32361371, 0.81354502, 0.69740038]])

In [11]:
import pandas as pd

In [12]:
df=pd.DataFrame(data=sdr)
df

0         1         2
0    0.548814  0.715189  0.602763
1    0.544883  0.423655  0.645894
2    0.437587  0.891773  0.963663
3    0.383442  0.791725  0.528895
4    0.568045  0.925597  0.071036
..        ...       ...       ...
995  0.698630  0.503697  0.025738
996  0.774353  0.560374  0.082494
997  0.475214  0.287293  0.879682
998  0.284927  0.941687  0.546133
999  0.323614  0.813545  0.697400

[1000 rows x 3 columns]

In [13]:
# Pseudo_random numbers - It will keep the random no. same evrey time
np.random.seed(seed=0)
ae = np.random.rand(8,8)
ae

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
        0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492, 0.56804456,
        0.92559664, 0.07103606, 0.0871293 ],
       [0.0202184 , 0.83261985, 0.77815675, 0.87001215, 0.97861834,
        0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329, 0.94466892, 0.52184832,
        0.41466194, 0.26455561, 0.77423369],
       [0.45615033, 0.56843395, 0.0187898 , 0.6176355 , 0.61209572,
        0.616934  , 0.94374808, 0.6818203 ],
       [0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 0.66676672,
        0.67063787, 0.21038256, 0.1289263 ],
       [0.31542835, 0.36371077, 0.57019677, 0.43860151, 0.98837384,
        0.10204481, 0.20887676, 0.16130952],
       [0.65310833, 0.2532916 , 0.46631077, 0.24442559, 0.15896958,
        0.11037514, 0.65632959, 0.13818295]])

In [14]:
np.random.seed(seed=0)
b=np.random.randint(1,5 , size=(3,5))
a

array([[0.32716044, 0.05874662],
       [0.57523031, 0.95942173],
       [0.63880329, 0.766157  ],
       [0.99988233, 0.56542887],
       [0.69094525, 0.331489  ],
       [0.1940203 , 0.07187287],
       [0.25655631, 0.36062988],
       [0.93915152, 0.64274397]])

In [15]:
d = pd.DataFrame(data=a)
d


0         1
0  0.327160  0.058747
1  0.575230  0.959422
2  0.638803  0.766157
3  0.999882  0.565429
4  0.690945  0.331489
5  0.194020  0.071873
6  0.256556  0.360630
7  0.939152  0.642744

In [41]:
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
a+b

array([[ 1,  5,  4,  4,  8],
       [ 9, 10, 11, 10, 13],
       [12, 14, 13, 17, 17]])

In [18]:
a*b

array([[ 0,  4,  4,  3, 16],
       [20, 24, 28, 16, 36],
       [20, 33, 12, 52, 42]])

In [19]:
a/b

array([[ 0.        ,  0.25      ,  1.        ,  3.        ,  1.        ],
       [ 1.25      ,  1.5       ,  1.75      ,  4.        ,  2.25      ],
       [ 5.        ,  3.66666667, 12.        ,  3.25      ,  4.66666667]])

In [20]:
a//b

array([[ 0,  0,  1,  3,  1],
       [ 1,  1,  1,  4,  2],
       [ 5,  3, 12,  3,  4]], dtype=int32)

In [21]:
a%b

array([[0, 1, 0, 0, 0],
       [1, 2, 3, 0, 1],
       [0, 2, 0, 1, 2]], dtype=int32)

In [22]:
np.max(a)

14

In [23]:
np.min(a)

0

In [24]:
np.sum(a)

105

In [25]:
np.std(a)

4.320493798938574

In [26]:
np.var(a)

18.666666666666668

In [27]:
# Transpose = It switches the axis'
a.shape

(3, 5)

In [28]:
a.T.shape # using transpose

(5, 3)

# Dot Product

In [42]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
b

array([[1, 4, 2, 1, 4],
       [4, 4, 4, 2, 4],
       [2, 3, 1, 4, 3]])

In [31]:
np.dot(a,b)

ValueError: shapes (3,5) and (3,5) not aligned: 5 (dim 1) != 3 (dim 0)

In [43]:
a.shape

(3, 5)

In [44]:
b.shape

(3, 5)

In [45]:
c=b.T

In [46]:
c

array([[1, 4, 2],
       [4, 4, 3],
       [2, 4, 1],
       [1, 2, 4],
       [4, 4, 3]])

In [47]:
c.shape

(5, 3)

In [48]:
np.dot(a,c)

array([[ 27,  34,  29],
       [ 87, 124,  94],
       [147, 214, 159]])