In [1]:
import numpy as np

In [23]:
a=np.arange(20).reshape(2,10)
b=np.arange(21,41).reshape(2,10)

In [25]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [26]:
b

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [27]:
np.hstack((a,b))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 21, 22, 23, 24, 25, 26,
        27, 28, 29, 30],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40]])

In [24]:
np.vstack((a,b))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [3]:
arr=np.array([[1,2,3,4,5],[2,3,4,5,6],[9,7,6,8,9]])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [4]:
arr[1:,2:4]

array([[4, 5],
       [6, 8]])

In [6]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [18]:
for a in np.nditer(arr,order='c',flags=['external_loop']):
    print(a)

1
2
3
4
5
2
3
4
5
6
9
7
6
8
9
